# Assignment-03-Q1-Hypothesis-Testing-
#Assume Null hyposthesis as Ho: μ1 = μ2 (There is no difference in diameters of cutlets between two units).
#Thus Alternate hypothesis as H1: μ1 ≠ μ2 (There is significant difference in diameters of cutlets between two units) 2 Sample 2 Tail test applicable
#Ho:u1=u2=u1-u2=0
#H1:u1!=u2=u1-u2!=0

if p-value is > 0.05 => Accept null hypothesis
if p-value is < 0.05 =>Reject null hypothesis

In [19]:
from scipy import stats
import pandas as pd 

In [20]:
df =pd.read_csv('Cutlets.csv')

In [21]:
df

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [22]:
unitA=pd.Series(df.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [23]:
unitB=pd.Series(df.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [24]:
stats.ttest_ind(unitA,unitB) 

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [25]:
import statsmodels.api as sm

In [26]:
sm.stats.ttest_ind(unitA,unitB)

(0.7228688704678063, 0.4722394724599501, 68.0)

In [27]:
#pvalue = 0.472>0.05 so Accept null hypotesis

# Q2

In [28]:
# Ho: u1=u2=u3=u4 > 0.05 Null hypotesis
# One difference < 0.05 Alternate hypotesis
import pandas as pd
import numpy as np
import scipy 
from scipy import stats


In [35]:
hos =pd.read_csv('LabTAT.csv')
print(hos) 
hos.columns="Laboratory 1","Laboratory 2","Laboratory 3","Laboratory 4"
stats.f_oneway(hos.iloc[:,0], hos.iloc[:,1],hos.iloc[:,2],hos.iloc[:,3]) 

     Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]


F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [36]:
#pvalue =2.11>0.05  Accept null hypotesis

#  Q3


In [37]:
#Ho p1=p2=p3=p4
#H1 atleast one difference
#Using  chi-square test
buy =pd.read_csv('BuyerRatio.csv')
buy

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [38]:
df_table=buy.iloc[:,1:6]
df_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [44]:
Chisquares_results=scipy.stats.chi2_contingency(df_table)
Chisquares_results


(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [45]:
#x value= 1.595945538661058 p value=0.6603094907091882 df=3
# Pvalue < alpha   0.66 < 1.59  we reject Null Hypothesis

# Q4


In [46]:
#Ho p1=p2=p3=p4 -->four centers
#H1 atleast one difference
#Using  chi-square test

In [47]:
df =pd.read_csv('Costomer+OrderForm.csv')

In [48]:
df

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [52]:
df1=df.iloc[:,0:5]
df1

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [55]:
df.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [56]:
df.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [58]:
df.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [59]:
df.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [60]:
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [64]:
from scipy.stats import chi2_contingency
chi2_contingency(obs)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [ ]:
#0.277 > 0.005  Pvalue >0.005 It's null hypotesis  